export default {
  // APP
  UPDTAE_SORTING: 'UPDTAE_SORT_BY',
  UPDATE_SEARCH_BY: 'UPDATE_SEARCH_BY',
  UPDATE_SEARCH_QUERY: 'UPDATE_SEARCH_QUERY',

  // DATA
  FETCHING_DATA: 'FETCHING_DATA',
  FETCHING_DATA_SUCCESS: 'FETCHING_DATA_SUCCESS',
  FETCHING_DATA_ERROR: 'FETCHING_DATA_ERROR',
};
